# Generated by Django 5.1 on 2024-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
