# Generated by Django 5.1.4 on 2025-01-04 12:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
