# Generated by Django 5.1.4 on 2025-01-05 06:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image (e.g., from Google Drive)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(help_text='Author of the post', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(help_text='Main category of the post', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(help_text='Content of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the post', null=True, upload_to='temp_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the post URL', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.CharField(help_text='Sub-category of the post', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of the post', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for the last update'),
        ),
    ]
