# Generated by Django 5.1.4 on 2025-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('poster_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('poster_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('download_link', models.URLField(max_length=500)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama')], max_length=100)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('Abhay Thakur', 'Abhay Thakur'), ('Ashish Ala', 'Ashish Ala')], max_length=100)),
            ],
        ),
    ]
