# Generated by Django 5.1.4 on 2025-01-04 12:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemovie',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
