# Generated by Django 5.1.4 on 2025-01-05 08:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_animemovie_poster_1_url_animemovie_poster_2_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemovie',
            name='author',
            field=models.CharField(choices=[('Abhay Thakur', 'Abhay Thakur'), ('Ashish Ala', 'Ashish Ala')], help_text='Author of the movie entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='description',
            field=tinymce.models.HTMLField(help_text='Detailed description of the movie'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='download_link',
            field=models.URLField(help_text='Direct download link for the anime movie', max_length=500),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama')], help_text='Genre of the movie', max_length=100),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_1',
            field=models.ImageField(blank=True, help_text='Upload the first poster', null=True, upload_to='temp_images/'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_1_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for the first poster', null=True),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_2',
            field=models.ImageField(blank=True, help_text='Upload the second poster', null=True, upload_to='temp_images/'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_2_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for the second poster', null=True),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_3',
            field=models.ImageField(blank=True, help_text='Upload the third poster', null=True, upload_to='temp_images/'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='poster_3_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for the third poster', null=True),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='release_date',
            field=models.DateField(help_text='Release date of the anime movie'),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='title',
            field=models.CharField(help_text='Title of the anime movie', max_length=200),
        ),
    ]
